#!/bin/bash

# link lnd datadir to default location
mkdir -p /data/lnd
ln -s /data/lnd /root/.lnd

if [[ ! -f /root/.lnd/lnd.conf ]]
then
	cp /usr/src/app/lnd.conf /root/.lnd/lnd.conf
fi

while [[ true ]]; do
 echo "hi";
 sleep 60;
done